### PR TITLE
Update tool_list.yaml

### PR DESCRIPTION
**Pull request by rmassei**
Added the DR curve tool developed in UFZ

### CODE REVIEW

**Comment by bernt-matthias** [comment]
I will need to add the Section first. Should we also add the other tool in this section?

**Comment by rmassei** [comment]
@bernt-matthias yes, you are right, I will also add the other tool!

**Comment by bernt-matthias** [comment]
Add section `Toxicology`

- [x] to UFZ Galaxy https://git.ufz.de/it/eve/bioinf-ufz/-/merge_requests/15
- [x] to the yaml schema here https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/pull/9
- [ ] fix TS repo https://github.com/galaxyproject/galaxy/issues/18359
- [ ] Roll out new tool confif and restart UFZ Galaxy

**Comment by bernt-matthias** [comment]
@rmassei can you please rebase this branch to get the linting with the changes from https://github.com/Helmholtz-UFZ/ufz-galaxy-tools/pull/9?

**Comment by bernt-matthias** [comment]
Let's try despite of the error in toolshed. The tools should be installed automatically over the weekend.

**Pull request merged**
